version: "3.8"

services: 
  guane_inter:
    image: guane_intern_api
    build: ./
    environment: 
      - DB_URL="postgres://postgres:postgres:5432/guane_intern_db"
    depends_on:
      - postgres 
    ports: 
      - "8001:8000"    

  postgres:
    image: postgres
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/:/root/db/  

